#pragma once
#include "../dew.h"
API_BEGIN

int l_errno_error(lua_State* L, int err_no); // note: always returns 0
bool x_luaL_optboolean(lua_State* L, int index, bool default_value);

// dew_lua_arraylen returns the length of an array-optimized table, or U32_MAX if not an array.
// This function only works correctly for "strict" Lua tables as generated by dawn.
// I.e. either either strictly arrays '{1, "two"}' or dicts '{x=1, y="two"}'.
// It does NOT work correctly for mixed Lua tables like '{1, [2]="two"}'.
LUA_API lua_Unsigned dew_lua_arraylen(lua_State* L, int idx); // lapi.c

API_END
